
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost/demo
    username: demo
    password: demo1234

#mybatis:
#  typeAliasesPackage: jp.co.tlzs.department.four.demo01.model
#  config-location: classpath:mybatis-config.xml

logging:
  level:
    jp.co.tlzs.department.four.demo01.mapper: debug
