
spring:
  datasource:
    url: jdbc:mysql://demo.chen09.xyz/demo
    username: demo
    password: demo1234
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis:
#  typeAliasesPackage: jp.co.tlzs.department.four.demo01.model
#  config-location: classpath:mybatis-config.xml
