package jp.co.tlzs.department.four.demo01.model;

import java.time.LocalDateTime;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Mon Aug 10 01:37:27 JST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated Mon Aug 10 01:37:27 JST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.age
     *
     * @mbg.generated Mon Aug 10 01:37:27 JST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.use_flg
     *
     * @mbg.generated Mon Aug 10 01:37:27 JST 2020
     */
    private Boolean useFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.del_flg
     *
     * @mbg.generated Mon Aug 10 01:37:27 JST 2020
     */
    private Boolean delFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.created_at
     *
     * @mbg.generated Mon Aug 10 01:37:27 JST 2020
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.updated_at
     *
     * @mbg.generated Mon Aug 10 01:37:27 JST 2020
     */
    private LocalDateTime updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.created_user_id
     *
     * @mbg.generated Mon Aug 10 01:37:27 JST 2020
     */
    private Integer createdUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.updated_user_id
     *
     * @mbg.generated Mon Aug 10 01:37:27 JST 2020
     */
    private Integer updatedUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Mon Aug 10 01:37:27 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Mon Aug 10 01:37:27 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbg.generated Mon Aug 10 01:37:27 JST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbg.generated Mon Aug 10 01:37:27 JST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.age
     *
     * @return the value of user.age
     *
     * @mbg.generated Mon Aug 10 01:37:27 JST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.age
     *
     * @param age the value for user.age
     *
     * @mbg.generated Mon Aug 10 01:37:27 JST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.use_flg
     *
     * @return the value of user.use_flg
     *
     * @mbg.generated Mon Aug 10 01:37:27 JST 2020
     */
    public Boolean getUseFlg() {
        return useFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.use_flg
     *
     * @param useFlg the value for user.use_flg
     *
     * @mbg.generated Mon Aug 10 01:37:27 JST 2020
     */
    public void setUseFlg(Boolean useFlg) {
        this.useFlg = useFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.del_flg
     *
     * @return the value of user.del_flg
     *
     * @mbg.generated Mon Aug 10 01:37:27 JST 2020
     */
    public Boolean getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.del_flg
     *
     * @param delFlg the value for user.del_flg
     *
     * @mbg.generated Mon Aug 10 01:37:27 JST 2020
     */
    public void setDelFlg(Boolean delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.created_at
     *
     * @return the value of user.created_at
     *
     * @mbg.generated Mon Aug 10 01:37:27 JST 2020
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.created_at
     *
     * @param createdAt the value for user.created_at
     *
     * @mbg.generated Mon Aug 10 01:37:27 JST 2020
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.updated_at
     *
     * @return the value of user.updated_at
     *
     * @mbg.generated Mon Aug 10 01:37:27 JST 2020
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.updated_at
     *
     * @param updatedAt the value for user.updated_at
     *
     * @mbg.generated Mon Aug 10 01:37:27 JST 2020
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.created_user_id
     *
     * @return the value of user.created_user_id
     *
     * @mbg.generated Mon Aug 10 01:37:27 JST 2020
     */
    public Integer getCreatedUserId() {
        return createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.created_user_id
     *
     * @param createdUserId the value for user.created_user_id
     *
     * @mbg.generated Mon Aug 10 01:37:27 JST 2020
     */
    public void setCreatedUserId(Integer createdUserId) {
        this.createdUserId = createdUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.updated_user_id
     *
     * @return the value of user.updated_user_id
     *
     * @mbg.generated Mon Aug 10 01:37:27 JST 2020
     */
    public Integer getUpdatedUserId() {
        return updatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.updated_user_id
     *
     * @param updatedUserId the value for user.updated_user_id
     *
     * @mbg.generated Mon Aug 10 01:37:27 JST 2020
     */
    public void setUpdatedUserId(Integer updatedUserId) {
        this.updatedUserId = updatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Aug 10 01:37:27 JST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", age=").append(age);
        sb.append(", useFlg=").append(useFlg);
        sb.append(", delFlg=").append(delFlg);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", createdUserId=").append(createdUserId);
        sb.append(", updatedUserId=").append(updatedUserId);
        sb.append("]");
        return sb.toString();
    }
}