version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  build:
    - maven/compile
  test:
    - maven/test

workflows:
  build_and_test:
    jobs:
      - build
      - test # checkout, build, test, and upload test results
